HostelChai/urls.py
from django.contrib import admin
from django.urls import path, include
from main_app import urls as main_app_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(main_app_urls)),
]

main_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static
from . import views

handler500 = 'main_app.views.error_500'

app_name = 'main_app'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('setup_admin_page/', views.setup_admin_page, name='setup_admin_page'),
    path('setup_admin/', views.setup_admin, name='setup_admin'),
    path('requests_loader_page/', views.requests_loader_page, name='requests_loader_page'),
    path('requests_loader/', views.requests_loader, name='requests_loader'),
    path('ad_approval_page/', views.ad_approval_page, name='ad_approval_page'),
    path('approve_ad/<ads_id>/', views.approve_ad, name='approve_ad'),
    path('hostel_approval_page/', views.hostel_approval_page, name='hostel_approval_page'),
    path('approve_hostel/', views.approve_hostel, name='approve_hostel'),
    path('user_approval_page/', views.user_approval_page, name='user_approval_page'),
    path('approve_user/<user_id>/<int:user_type>/', views.approve_user, name='approve_user'),
    path('registration_page/', views.registration_page, name='registration_page'),
    path('student_registration/', views.student_registration, name='student_registration'),
    path('hostel_owner_registration/', views.hostel_owner_registration, name='hostel_owner_registration'),
    path('login_page/', views.login_page, name='login_page'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('home_page/', views.home_page, name='home_page'),
    path('admin_home_page/', views.admin_home_page, name='admin_home_page'),
    path('student_home_page/', views.student_home_page, name='student_home_page'),
    path('hostel_owner_home_page/', views.hostel_owner_home_page, name='hostel_owner_home_page'),
    path('profile_page/<int:user>/<user_id>/', views.profile_page, name='profile_page'),
    path('admin_profile_page/<user_id>/', views.admin_profile_page, name='admin_profile_page'),
    path('student_profile_page/<user_id>/', views.student_profile_page, name='student_profile_page'),
    path('hostel_owner_profile_page/<user_id>/', views.profile_page, name='hostel_owner_profile_page'),
    path('add_hostel_page/', views.add_hostel_page, name='add_hostel_page'),
    path('add_hostel/', views.add_hostel, name='add_hostel'),
    path('process_hostel_review_and_rating/<user_id>/<hostel_id>/', views.process_hostel_review_and_rating, name='process_hostel_review_and_rating'),
    path('ad_posting_page/', views.ad_posting_page, name='ad_posting_page'),
    path('ad_posting/', views.ad_posting, name='ad_posting'),
    path('ads_feed_page/<int:page_number>/<location>/<institute>/<budget_from>/<budget_to>/', views.ads_feed_page, name='ads_feed_page'),
    path('complaint_box_page/', views.complaint_box_page, name='complaint_box_page'),
    path('complaint_box/', views.complaint_box, name='complaint_box'),
    path('complaint_checker_page/<complaint_id>/', views.complaint_checker_page, name='complaint_checker_page'),
    path('complaint_checker_page/', views.complaint_checker_page, name='complaint_checker_page'),
    path('resolve_complaint/<complaint_id>/', views.resolve_complaint, name='resolve_complaint'),
    path('test_page/', views.test_page, name='test_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models

# Create your models here.

main_app/views.py
from my_modules import page_works, exceptions, classes, database, utilities
from django.shortcuts import render
from django.db import connection
from pathlib import Path
import datetime
import math
import os

cursor = connection.cursor()

base_dir = Path('__file__').resolve().parent.parent
text_files_dir = os.path.join(base_dir, 'text_files')
temp_files_dir = os.path.join(base_dir, 'temp_files')


def test_page(request):

    data_dict = {
        'page_name': 'test_page',
    }

    user_dict = page_works.get_active_user(request)

    try:
        data_dict['user_id'] = user_dict['user_id']
        data_dict['name'] = user_dict['name']
        data_dict['user_type'] = user_dict['user_type']
        data_dict['login_status'] = 'true'
    except KeyError:
        data_dict['login_status'] = 'false'

    data_dict['image'] = 'H-1_HOS-4_electbill.png'

    data_dict['days'] = range(32)[1:]
    data_dict['months'] = 'January,February,March,April,May,June,July,August,September,October,November,December'.split(',')
    data_dict['years'] = range(2022)[1990:]

    return render(request, 'main_app/test_page.html', context=data_dict)


def setup_admin_page(request):
    return render(request, 'main_app/setup_admin_page.html', context={})


def setup_admin(request):

    name = request.POST.get('name')
    username = request.POST.get('username')
    password = request.POST.get('password')
    gender = request.POST.get('gender')
    phone = request.POST.get('phone')
    email = request.POST.get('email')
    address = request.POST.get('address')

    command = f'select count(*) from user where id like "A%"'
    cursor.execute(command)
    user_id = f'A-{cursor.fetchall()[0][0] + 1}'

    command = f'insert into user values ("{user_id}", "{name}", "{username}", "{password}", "null", CURRENT_DATE , "null", "null", "{gender}", "{phone}", "{email}", "{address}", 1, 9)'
    cursor.execute(command)

    return login_page(request)


def error_404(request, exception=''):

    try:
        page_works.request_verify(request, True)

        user_dict = page_works.get_active_user(request)

        data_dict = {
            'name': user_dict['name'],
            'logged_in_username': user_dict['username'],
            'user_type': user_dict['user_type'],
            'page_name': '404_page',
            'login_status': 'true',
        }

    except exceptions.LoginRequiredException:
        pass

    return render(request, 'main_app/404_page.html', context=data_dict)


def error_500(request, template_name='500.html'):

    data_dict = {}

    try:
        page_works.request_verify(request, True)

        user_dict = page_works.get_active_user(request)

        data_dict = {
            'name': user_dict['name'],
            'logged_in_username': user_dict['username'],
            'user_type': user_dict['user_type'],
            'page_name': '404_page',
            'login_status': 'true',
        }
    except exceptions.LoginRequiredException:
        pass

    return render(request, template_name, context=data_dict)


def requests_loader_page(request):

    try:
        page_works.request_verify(request, True)
    except exceptions.LoginRequiredException:
        return login_page(request)

    try:
        page_works.user_verify(request, 'A')
    except exceptions.UserRequirementException:
        return home_page(request)

    user_dict = page_works.get_active_user(request)

    data_dict = {
        'user_id': user_dict['user_id'],
        'name': user_dict['name'],
        'logged_in_username': user_dict['username'],
        'user_type': user_dict['user_type'],
        'page_name': 'admin_hostel_loader_page',
        'login_status': 'true',
    }

    command = 'select id from user where verified=0'
    cursor.execute(command)
    users = [user[0] for user in cursor.fetchall()]

    command = 'select hostel_id from hostel where verified=0'
    cursor.execute(command)
    hostels = [hostel[0] for hostel in cursor.fetchall()]

    command = 'select ads_id from advertise where approved=0'
    cursor.execute(command)
    ads = [ad[0] for ad in cursor.fetchall()]

    data_dict['users'] = users
    data_dict['hostels'] = hostels
    data_dict['ads'] = ads

    return render(request, 'main_app/requests_loader_page.html', context=data_dict)


def requests_loader(request):

    try:
        page_works.request_verify(request, True)
    except exceptions.LoginRequiredException:
        return login_page(request)

    try:
        page_works.user_verify(request, 'A')
    except exceptions.UserRequirementException:
        return home_page(request)

    req_type = request.POST.get('req_type')

    if req_type == 'hostels':
        return hostel_approval_page(request)
    elif req_type == 'ads':
        return ad_approval_page(request)
    elif req_type == 'users':
        return user_approval_page(request)
    else:
        return home_page(request)


def ad_approval_page(request):

    try:
        page_works.request_verify(request, True)
    except exceptions.LoginRequiredException:
        return login_page(request)

    try:
        page_works.user_verify(request, 'A')
    except exceptions.UserRequirementException:
        return home_page(request)

    ads_id = request.POST.get('ads_id')

    if not ads_id:
        return requests_loader_page(request)

    user_dict = page_works.get_active_user(request)

    data_dict = {
        'user_id': user_dict['user_id'],
        'name': user_dict['name'],
        'logged_in_username': user_dict['username'],
        'user_type': user_dict['user_type'],
        'page_name': 'admin_home_page',
        'login_status': 'true',
        'ads_id': ads_id,
    }

    return render(request, 'main_app/ad_approval_page.html', context=data_dict)


def approve_ad(request, ads_id):

    try:
        page_works.request_verify(request, True)
    except exceptions.LoginRequiredException:
        return login_page(request)

    try:
        page_works.user_verify(request, 'A')
    except exceptions.UserRequirementException:
        return home_page(request)

    ad = classes.Advertise()
    ad.load(ads_id)
    ad.approved = 1
    ad.active = 1
    ad.save()

    return requests_loader_page(request)


def hostel_approval_page(request):

    try:
        page_works.request_verify(request, True)
    except exceptions.LoginRequiredException:
        return login_page(request)

    try:
        page_works.user_verify(request, 'A')
    except exceptions.UserRequirementException:
        return home_page(request)

    hostel_id = request.POST.get('hostel_id')

    if hostel_id:

        hostel = classes.Hostel()
        hostel.load(hostel_id)

        command = f'select name, phone_number from user where id like "{hostel.hostel_owner_id}"'
        cursor.execute(command)

        hostel_owner_name, phone_number = cursor.fetchall()[0]

        user_dict = page_works.get_active_user(request)

        data_dict = {
            'user_id': user_dict['user_id'],
            'name': user_dict['name'],
            'logged_in_username': user_dict['username'],
            'user_type': user_dict['user_type'],
            'page_name': 'admin_home_page',
            'login_status': 'true',
            'hostel_name': hostel.hostel_name,
            'hostel_owner_name': hostel_owner_name,
            'phone_number': phone_number,
            'hostel_id': hostel.hostel_id,
            'hostel_house_number': hostel.house_number,
            'hostel_road_number': hostel.road_number,
            'hostel_thana': hostel.thana,
            'hostel_postal_code': hostel.postal_code,
            'hostel_photo': hostel.photo,
            'hostel_electricity_bill': hostel.electricity_bill,
            'hostel_document': hostel.hostel_document,
        }

        return render(request, 'main_app/hostel_approval_page.html', context=data_dict)
    else:
        return requests_loader_page(request)


def approve_hostel(request):

    try:
        page_works.request_verify(request, True)
    except exceptions.LoginRequiredException:
        return login_page(request)

    try:
        page_works.user_verify(request, 'A')
    except exceptions.UserRequirementException:
        return home_page(request)

    hostel_id = request.POST.get('hostel_id')
    command = f'update hostel set verified=1, active=1 where hostel_id like "{hostel_id}"'
    cursor.execute(command)

    return requests_loader_page(request)


def user_approval_page(request):

    try:
        page_works.request_verify(request, True)
    except exceptions.LoginRequiredException:
        return login_page(request)

    try:
        page_works.user_verify(request, 'A')
    except exceptions.UserRequirementException:
        return home_page(request)

    user_dict = page_works.get_active_user(request)

    user_id = request.POST.get('user_id')

    if user_id:

        data_dict = {
            'user_id': user_dict['user_id'],
            'name': user_dict['name'],
            'logged_in_username': user_dict['username'],
            'user_type': user_dict['user_type'],
            'page_name': 'admin_home_page',
            'login_status': 'true',

            'user_id_': user_id,
            'user_type_': 0 if user_id.split('-')[0] == 'S' else 1,
        }

        return render(request, 'main_app/user_approval_page.html', context=data_dict)

    else:
        return requests_loader_page(request)


def approve_user(request, user_id, user_type):

    try:
        page_works.request_verify(request, True)
    except exceptions.LoginRequiredException:
        return login_page(request)

    try:
        page_works.user_verify(request, 'A')
    except exceptions.UserRequirementException:
        return home_page(request)

    if user_type == 0:
        student = classes.Student()
        student.load_student(user_id)
        student.verified = 1
        student.active = 1
        student.save_student()
    else:
        hostel_owner = classes.HostelOwner()

templates/main_app/ad_approval_page.html
<!DOCTYPE html>
{% extends "main_app/page_template.html" %}

    {% load static %}

    {% block title %}
        Hostel Chai ?
    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static "main_app/stylesheets/ad_approval_page.css" %}">
    {% endblock %}

    {% block my_js %}
        <script src="{% static "main_app/js/ad_approval_page.js" %}"></script>
    {% endblock %}

    {% block main_block %}

        <div class="jumbotron header_layer_1 bg-transparent">
            <div class="jumbotron header_layer_2 bg-transparent">
                <h1 class="text-info text-center header">{{ ads_id }}</h1>
            </div>
        </div>

        <div class="jumbotron jumbotron_suffix bg-dark">
            <h1 class="text-center text-secondary">Information will appear here.</h1>

            <br>

            <div class="row">
                <div class="col">
                    <a class="btn btn-outline-secondary btn-block" href="{% url 'main_app:requests_loader_page' %}">Check Another</a>
                </div>
                <div class="col">
                    <a class="btn btn-outline-success btn-block" href="{% url 'main_app:approve_ad' ads_id=ads_id %}">Approve</a>
                </div>
            </div>
        </div>

    {% endblock %}

templates/main_app/admin_home_page.html
<!DOCTYPE html>
{% extends "main_app/page_template.html" %}

    {% load static %}

    {% block title %}
        Hostel Chai ?
    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static "main_app/stylesheets/admin_home_page.css" %}">
    {% endblock %}

    {% block my_js %}
        <script src="{% static "main_app/js/admin_home_page.js" %}"></script>
    {% endblock %}

    {% block main_block %}
        <div class="jumbotron header_layer_1 bg-transparent">
            <div class="jumbotron header_layer_2 bg-transparent">
                <h1 class="text-info text-center header">{{ name }}</h1>
            </div>
        </div>
    {% endblock %}

templates/main_app/admin_profile_page.html
<!DOCTYPE html>
{% extends "main_app/page_template.html" %}

    {% load static %}

    {% block title %}
        Hostel Chai ?
    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static "main_app/stylesheets/admin_profile_page.css" %}">
    {% endblock %}

    {% block my_js %}
        <script src="{% static "main_app/js/admin_profile_page.js" %}"></script>
    {% endblock %}

    {% block main_block %}       \
        <div class="jumbotron header_layer_1 bg-transparent">
            <div class="jumbotron header_layer_2 bg-transparent">
                <h1 class="text-info text-center header">Profile</h1>
            </div>
        </div>
    {% endblock %}

templates/main_app/ads_feed_page.html
<!DOCTYPE html>
{% extends "main_app/page_template.html" %}

    {% load static %}

    {% block title %}
        Hostel Chai ?
    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static "main_app/css/ads_feed_page.css" %}">
    {% endblock %}

    {% block my_js %}
        <script src="{% static "main_app/js/ads_feed_page.js" %}"></script>
    {% endblock %}

    {% block main_block %}

        <div class="jumbotron header_layer_1 bg-transparent">
            <div class="jumbotron header_layer_2 bg-transparent">
                <h1 class="text-info text-center header">Posts</h1>
            </div>
        </div>

        <form class="form-group" action="{% url 'main_app:ads_feed_page' page_number=0 location='null' institute='null' budget_from='null' budget_to='null' %}" method="post">

            {% csrf_token %}

            <div class="row">

                {% if login_status == 'false' or user_type == 'H' %}
                    <div class="col">
                {% else %}
                    <div class="col-3">
                {% endif %}
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-transparent border border-info text-info"><b>Location:</b></span>
                        </div>
                        <select class="custom-select bg-transparent border border-info text-info" name="location" id="location">
                            {% for thana in thanas %}
                                <option class="text-info bg-dark" value="{{ thana.0 }}" {{ thana.1 }}>{{ thana.0 }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                {% if login_status == 'true' and user_type != 'H' %}
                    <div class="col">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-transparent border border-info text-info"><b>Institute:</b></span>
                            </div>
                            <select class="custom-select bg-transparent border border-info text-info" name="institute" id="institute">
                                {% for institute in institutes %}
                                    <option class="text-info bg-dark" value="{{ institute.0 }}" {{ institute.1 }}>{{ institute.0 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-transparent border border-info text-info"><b>Budget:</b></span>
                            </div>
                            <input class="form-control bg-transparent border border-info text-info" type="text" name="budget_from" value="{{ budget_from }}" placeholder="Min" required>
                            <input class="form-control bg-transparent border border-info text-info" type="text" name="budget_to" value="{{ budget_to }}" placeholder="Max" required>
                        </div>
                    </div>
                {% endif %}
                <div class="col-1">
                    <input class="btn btn-outline-info btn-block" type="submit" value="Apply">
                </div>
            </div>
        </form>
        <br>

        <nav>
            <ul class="pagination justify-content-center">
                <li class="page-item"><a class="btn btn-outline-info" href="{% url 'main_app:ads_feed_page' page_number=previous_page location=url_location institute=url_institute budget_from=url_budget_from budget_to=url_budget_to %}">Previous</a></li>

                {% for page in pages %}
                    <li class="page-item"><a class="btn btn-outline-info {{ page.1 }}" href="{% url 'main_app:ads_feed_page' page_number=page.0 location=url_location institute=url_institute budget_from=url_budget_from budget_to=url_budget_to %}">{{ page.0 }}</a></li>
                {% endfor %}

                <li class="page-item"><a class="btn btn-outline-info" href="{% url 'main_app:ads_feed_page' page_number=next_page location=url_location institute=url_institute budget_from=url_budget_from budget_to=url_budget_to %}">Next</a></li>
            </ul>
        </nav>

        <br>

        {% for ad_row in ads %}
            <div class="row">
                {% for ad in ad_row %}
                    <div class="col-3">
                        <div class="card bg-dark text-info">
                            <img class="card-img-top" src="{{ MEDIA_URL }}{{ ad.0 }}_room_photo.png" height="200px"  alt="Image not found">
                            <div class="card-body">
                                <h5 class="card-title">{{ ad.1 }}</h5>
                                <p class="card-text">Rating: <span class="badge badge-success">{{ ad.2 }}</span></p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item bg-secondary text-light">
                                    <div class="row">
                                        <div class="col">
                                            Location
                                        </div>
                                        <div class="col">
                                          :  {{ ad.3 }}
                                        </div>
                                    </div>
                                </li>
                                <li class="list-group-item bg-secondary text-light">
                                    <div class="row">
                                        <div class="col">
                                            Institution preference
                                        </div>
                                        <div class="col">
                                            : {{ ad.4 }}
                                        </div>
                                    </div>
                                </li>
                                <li class="list-group-item bg-secondary text-light">
                                    <div class="row">
                                        <div class="col">
                                            Rent
                                        </div>
                                        <div class="col">
                                            : {{ ad.5 }}/=
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <div class="card-body">
                                {% if login_status == 'true' %}
                                    <a class="btn btn-outline-secondary btn-block" href="#">View details</a>
                                {% else %}
                                    <a class="btn btn-outline-secondary btn-block" href="{% url 'main_app:login_page' %}">View details</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <br>
        {% endfor %}
    {% endblock %}

templates/main_app/complaint_box_page.html
<!DOCTYPE html>
{% extends "main_app/page_template.html" %}

    {% load static %}

    {% block title %}
        Hostel Chai ?
    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static "main_app/stylesheets/complaint_box_page.css" %}">
    {% endblock %}

    {% block my_js %}
        <script src="{% static "complaint_box_page/js/file_name.js" %}"></script>
    {% endblock %}

    {% block main_block %}

        <div class="jumbotron header_layer_1 bg-transparent">
            <div class="jumbotron header_layer_2 bg-transparent">
                <h1 class="text-info text-center header">Complaint Box</h1>
            </div>
        </div>

        <div class="jumbotron jumbotron_suffix bg-dark">
            <form class="form-group" action="{% url 'main_app:complaint_box' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <p>
                    <input class="form-control" type="text" name="subject" placeholder="Subject" required>
                </p>

                <p>
                    <textarea class="form-control" id="details" name="details" placeholder="Write details here ..." rows="3" required></textarea>
                </p>

                <p>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Attachment[as image]</span>
                        </div>

                        <div class="custom-file">
                            <input class="custom-file-input" id="photo" type="file" name="photo">
                            <label class="custom-file-label bg_custom" for="photo">Choose file</label>
                        </div>
                    </div>
                </p>

                <br>

                <input class="btn btn-outline-danger btn-block" type="submit" value="Submit">

            </form>
        </div>

    {% endblock %}

templates/main_app/complaint_checker_page.html
<!DOCTYPE html>
{% extends "main_app/page_template.html" %}

    {% load static %}

    {% block title %}
        Hostel Chai ?
    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static "main_app/stylesheets/complaint_checker_page.css" %}">
    {% endblock %}

    {% block my_js %}
        <script src="{% static "main_app/js/complaint_checker_page.js" %}"></script>
    {% endblock %}

    {% block main_block %}

        <div class="jumbotron header_layer_1 bg-transparent">
            <div class="jumbotron header_layer_2 bg-transparent">
                {% if loaded_complaint_id == 'null' or all_resolved == 'true' %}
                    <h1 class="text-center text-info header">Check complaints</h1>
                {% else %}
                    <h1 class="text-center text-info header">Complaint ID: {{ loaded_complaint_id }}</h1>
                {% endif %}
            </div>
        </div>

        {% if all_resolved == 'true' %}
            <div class="jumbotron jumbotron_suffix bg-dark">
                <h1 class="text-center text-secondary">No complaints to resolve.</h1>
            </div>
        {% else %}
            <div class="row">
                <div class="col">
                    <div class="input-group">
                        <select class="custom-select bg-secondary text-light border border-info" id="complaint_id" name="complaint_id">
                            {% for complaint in complaints %}
                                <option value={% url 'main_app:complaint_checker_page' complaint_id=complaint.0 %}>{{ complaint.0 }} {{ complaint.1 }}</option>
                            {% endfor %}
                        </select>
                        <div class="input-group-append">
                            <a class="btn btn-outline-info" id="load" href="#">Load</a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <a class="btn btn-outline-success btn-block" href="{% url 'main_app:resolve_complaint' complaint_id=loaded_complaint_id %}">Mark current complaint as resolved</a>
                </div>
            </div>

            <br>

            <div class="jumbotron jumbotron_suffix bg-dark">

                {% if loaded_complaint_id == 'null' %}
                    <h1 class="text-center text-secondary">Please load to check complaints</h1>
                {% else %}

                    <div class="jumbotron jumbotron_suffix_unified bg-secondary">
                        <div class="row">
                            <div class="col"><h3 class="text-dark">User: {{ loaded_user_id_name }}</h3></div>
                            <div class="col"><h3 class="text-dark">Contact: {{ loaded_user_contact.0 }}</h3></div>
                        </div>
                    </div>

                    <div class="jumbotron jumbotron_suffix_unified bg-secondary text-dark">
                        <div class="row">
                            <div class="col-2"><h3 class="text-dark">Subject</h3></div>
                            <div class="col"><h3 class="text-dark">: {{ loaded_complaint_subject }}</h3></div>
                        </div>

                        <p>

                        <div class="row">
                            <div class="col-2"><h3 class="text-dark">Details</h3></div>
                            <div class="col"><h3 class="text-dark">: {{ loaded_complaint_description }}</h3></div>
                        </div>
                    </div>

                    <p>

                    <h4 class="text-center text-secondary"><b>**ATTACHMENTS**</b></h4>

                    <p>

                    <div class="accordion" id="accordionExample">
                        <div class="card bg-secondary">
                            <div class="card-header" id="headingOne">
                                <h2 class="mb-0">
                                    <button class="btn btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        <span class="text-dark"><b>Toggle View</b></span>
                                    </button>
                                </h2>
                            </div>

                            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                                <div class="card-body">
                                    <img class="card-img" src="{{ MEDIA_URL }}{{ loaded_complaint_attachment }}" alt="Not found !!!">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endif %}
    {% endblock %}

templates/main_app/hostel_owner_home_page.html
<!DOCTYPE html>
{% extends "main_app/page_template.html" %}

    {% load static %}

    {% block title %}
        Hostel Chai
    {% endblock %}

    {% block my_stylesheet %}
        <link rel="stylesheet" href="{% static "main_app/stylesheets/hostel_owner_home_page.css" %}">
    {% endblock %}

    {% block my_js %}
        <script src="{% static "main_app/js/hostel_owner_home_page.js" %}"></script>
    {% endblock %}

    {% block main_block %}

        <div class="jumbotron header_layer_1 bg-transparent">
            <div class="jumbotron header_layer_2 bg-transparent">
                <h1 class="text-info text-center header">Welcome {{ name }}</h1>
            </div>
        </div>

    {% endblock %}